name: Checks

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
      - name: Install
        run: |
          npm install
      - name: Install browser dependencies
        run: |
          npx puppeteer browsers install chrome
          npx playwright install chromium
      - name: Audit
        run: |
          npm run audit
      - name: Lint
        run: |
          npm run lint
      - name: Tests
        run: |
          npm run test
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/lcov.info
          format: lcov
      - name: Build
        run: |
          npm run build
