name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: googleapis/release-please-action@v5
        with:
          release-type: node
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access=public
