name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: googleapis/release-please-action@v5
        with:
          release-type: node
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
      - name: Install
        run: npm install
      - name: Publish
        env:
          NPM_API_TOKEN: ${{ secrets.NPM_API_TOKEN }}
        run: |
          npm set //registry.npmjs.org/:_authToken $NPM_API_TOKEN
          npm publish --access=public
